// /apple/.test("appledddd")
// true
// /^\w@a.com$/.test("aaaa@a.com")
// false
// /\w@a.com/.test("aaaa@a.com")
// true
// /^\w+@a.com$/.test("aaaa@a.com")
// true
// /^\w?@a.com$/.test("aaaa@a.com")
// false
// /^\w@a.com$/.test("aaaa@a.com")
// true
// /^\w@\w+.\w+$/.test("aaaa@a.com")
// true
// /^\w@\w+.\w+$/.test("aaaa@a?com")
// true
// /^\w@\w+.\w+$/.test("aaaa@a?com")
// false
// /^\w*@\w+.\w+$/.test("aaaa@a.com")
// true
// /^010-1234-5678$/.test("010-1234-5678")
// true
// /^\d{3}-\d{3,4}-\d{4}$/.test("010-1234-5678")
// true
